//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkceWS
    {
        public int akceWS_Id { get; set; }
        public int bodAP_Id { get; set; }
        public string napravnaOpatreni { get; set; }
        public int odpovednaOsoba1 { get; set; }
        public Nullable<int> odpovednaOsoba2 { get; set; }
        public Nullable<System.DateTime> kontrolaEfektivnosti { get; set; }
        public Nullable<int> oddeleni_Id { get; set; }
        public string priloha { get; set; }
        public bool storno { get; set; }
    }
}
