//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkcniPlan
    {
        public int AkcniPlanID { get; set; }
        public int CisloAP { get; set; }
        public int Rok { get; set; }
        public int Zadavatel1ID { get; set; }
        public Nullable<int> Zadavatel2ID { get; set; }
        public string Tema { get; set; }
        public Nullable<int> ProjektID { get; set; }
        public System.DateTime DatumZalozeni { get; set; }
        public Nullable<System.DateTime> DatumUkonceni { get; set; }
        public int ZakaznikID { get; set; }
        public bool AudityOstatni { get; set; }
    }
}
