//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkcniPlany
    {
        public int akcniPlan_Id { get; set; }
        public int cisloAP { get; set; }
        public int rok { get; set; }
        public int zadavatel1_Id { get; set; }
        public Nullable<int> zadavatel2_Id { get; set; }
        public string tema { get; set; }
        public Nullable<int> projekt_Id { get; set; }
        public System.DateTime datumZalozeni { get; set; }
        public int zakaznik_Id { get; set; }
        public bool audityOstatni { get; set; }
    }
}
