//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodAP
    {
        public int BodAPID { get; set; }
        public int AkcniPlanID { get; set; }
        public bool AudityOstatni { get; set; }
        public int CisloBoduAP { get; set; }
        public System.DateTime DatumZalozeni { get; set; }
        public string OdkazNaNormu { get; set; }
        public string HodnoceniNeshody { get; set; }
        public string PopisProblemu { get; set; }
        public string SkutecnaPricina { get; set; }
        public bool Storno { get; set; }
    }
}
