//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyAP
    {
        public int bodAP_Id { get; set; }
        public int akcniPlan_Id { get; set; }
        public bool audityOstatni { get; set; }
        public int cisloBoduAP { get; set; }
        public System.DateTime datumZalozeni { get; set; }
        public string odkazNaNormu { get; set; }
        public string hodnoceniNeshody { get; set; }
        public string popisProblemu { get; set; }
        public string skutecnaPricina { get; set; }
        public string APIdBodAP { get; set; }
        public bool storno { get; set; }
    }
}
