//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatumUkonceniAkceWS
    {
        public int datumUkonceniAkceWS_Id { get; set; }
        public int akceWS_Id { get; set; }
        public System.DateTime datumUkonceni { get; set; }
        public string poznamka { get; set; }
    }
}
