//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearDataAllEntities : DbContext
    {
        public LearDataAllEntities()
            : base("name=LearDataAllEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AkceWM> AkceWM { get; set; }
        public virtual DbSet<AkceWS> AkceWS { get; set; }
        public virtual DbSet<AkcniPlan> AkcniPlan { get; set; }
        public virtual DbSet<BodAP> BodAP { get; set; }
        public virtual DbSet<Oddeleni> Oddeleni { get; set; }
        public virtual DbSet<Projekt> Projekt { get; set; }
        public virtual DbSet<UkonceniAkceWM> UkonceniAkceWM { get; set; }
        public virtual DbSet<UkonceniAP> UkonceniAP { get; set; }
        public virtual DbSet<Zakaznik> Zakaznik { get; set; }
        public virtual DbSet<Zamestnanec> Zamestnanec { get; set; }
        public virtual DbSet<UkonceniAkceWS> UkonceniAkceWS { get; set; }
    }
}
