//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearDataAllEntities : DbContext
    {
        public LearDataAllEntities()
            : base("name=LearDataAllEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AkceWM> AkceWM { get; set; }
        public virtual DbSet<AkceWS> AkceWS { get; set; }
        public virtual DbSet<AkcniPlany> AkcniPlany { get; set; }
        public virtual DbSet<BodyAP> BodyAP { get; set; }
        public virtual DbSet<DatumUkonceniAkceWM> DatumUkonceniAkceWM { get; set; }
        public virtual DbSet<DatumUkonceniAP> DatumUkonceniAP { get; set; }
        public virtual DbSet<Oddeleni> Oddeleni { get; set; }
        public virtual DbSet<Projekty> Projekty { get; set; }
        public virtual DbSet<Zakaznici> Zakaznici { get; set; }
        public virtual DbSet<Zamestnanci> Zamestnanci { get; set; }
        public virtual DbSet<DatumUkonceniAkceWS> DatumUkonceniAkceWS { get; set; }
    }
}
