//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oddeleni
    {
        public int OddeleniID { get; set; }
        public string Nazev { get; set; }
        public bool Storno { get; set; }
    }
}
