//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UkonceniAkce
    {
        public int UkonceniAkceID { get; set; }
        public int AkceID { get; set; }
        public System.DateTime DatumUkonceni { get; set; }
        public string Poznamka { get; set; }
    }
}
