//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamestnanci
    {
        public int zamestnanec_Id { get; set; }
        public string jmeno { get; set; }
        public string prijmeni { get; set; }
        public int personalniCislo { get; set; }
        public int oddeleni_Id { get; set; }
        public string email { get; set; }
        public bool jeZamestnanec { get; set; }
        public bool storno { get; set; }
    
        public virtual Oddeleni Oddeleni { get; set; }
    }
}
