//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearActionPlans.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamestnanec
    {
        public int ZamestnanecID { get; set; }
        public string Jmeno { get; set; }
        public string Prijmeni { get; set; }
        public string PersonalniCislo { get; set; }
        public int OddeleniID { get; set; }
        public string Email { get; set; }
        public bool JeZamestnanec { get; set; }
        public bool Storno { get; set; }
    }
}
