USE [LearDataAll]
GO

/****** Object:  Table [dbo].[Zakaznik]    Script Date: 01.08.2021 11:44:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Zakaznik](
	[ZakaznikID] [int] IDENTITY(1,1) NOT NULL,
	[Nazev] [nvarchar](30) NOT NULL,
	[Storno] [bit] NOT NULL,
 CONSTRAINT [PK_Zakaznici] PRIMARY KEY CLUSTERED 
(
	[ZakaznikID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Zakaznik] ADD  CONSTRAINT [DF_Zakaznici_storno]  DEFAULT ((0)) FOR [Storno]
GO

